server:
  port: 8088
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000  #文件上传的大小限制 500kb
      max-request-size: 512000 #请求大小限制为 500kb


mybatis:
  type-aliases-package: com.wang.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  mappers: com.wang.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

